// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBz-7geJs1IJTzh-7sDf1Cgs5doQeWzLw0',
    appId: '1:527509341516:web:e873377b178ffbd8d7bbe9',
    messagingSenderId: '527509341516',
    projectId: 'counterfirebase-a3bd2',
    authDomain: 'counterfirebase-a3bd2.firebaseapp.com',
    storageBucket: 'counterfirebase-a3bd2.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAsYkt2zry86HX8D7G1LrWdGWMxcFKwZPI',
    appId: '1:527509341516:android:031d38f7ed84bff0d7bbe9',
    messagingSenderId: '527509341516',
    projectId: 'counterfirebase-a3bd2',
    storageBucket: 'counterfirebase-a3bd2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA8QJl_QJwj-ohQ7ocoaC5_DZG9l5gBcQs',
    appId: '1:527509341516:ios:18d219e00e7c6d27d7bbe9',
    messagingSenderId: '527509341516',
    projectId: 'counterfirebase-a3bd2',
    storageBucket: 'counterfirebase-a3bd2.appspot.com',
    iosClientId: '527509341516-aq3c9ncb6hjost1neir7vue9druaa93g.apps.googleusercontent.com',
    iosBundleId: 'com.example.counterFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA8QJl_QJwj-ohQ7ocoaC5_DZG9l5gBcQs',
    appId: '1:527509341516:ios:18d219e00e7c6d27d7bbe9',
    messagingSenderId: '527509341516',
    projectId: 'counterfirebase-a3bd2',
    storageBucket: 'counterfirebase-a3bd2.appspot.com',
    iosClientId: '527509341516-aq3c9ncb6hjost1neir7vue9druaa93g.apps.googleusercontent.com',
    iosBundleId: 'com.example.counterFirebase',
  );
}
